SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ItemsType](
	[ItemsTypeID] [nvarchar](20) NOT NULL,
	[ItemsTypeName] [nvarchar](20) NULL,
	[IsEnable] [bit] NULL,
 CONSTRAINT [PK_ItemsType] PRIMARY KEY CLUSTERED 
(
	[ItemsTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


