SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TakeStockMaster](
	[TakeStockID] [nvarchar](20) NOT NULL,
	[TakeStockDate] [nvarchar](12) NULL,
	[TakeStockStaff] [nvarchar](30) NULL,
	[Notes] [nvarchar](max) NULL,
 CONSTRAINT [PK_TakeStockMaster] PRIMARY KEY CLUSTERED 
(
	[TakeStockID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


